Repository googleapis/nodejs-access-approval, pull requests merged in 2021-02, with the labels that each got.

#12 chore: update CODEOWNERS config
  .github/CODEOWNERS
Labels: automerge, cla: yes

#11 build: migrate to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
Labels: automerge, cla: yes

#15 chore: update flakybot config and package name in docs
  .jsdoc.js
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  README.md
  linkinator.config.json
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/access_approval_client.ts
  src/v1/gapic_metadata.json
  src/v1/index.ts
  synth.metadata
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
  test/gapic_access_approval_v1.ts
Labels: cla: yes, context: partial

#16 chore: update flakybot config and a few docs
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  CONTRIBUTING.md
  README.md
  synth.metadata
Labels: cla: yes, context: full

#17 build: config for owlbot
  .github/.OwlBot.yaml
  owlbot.py
Labels: api: accessapproval, cla: yes
